export {default as productService} from './products'
export {default as stockService} from './stock'
export {order as orderService} from './orders'
export {default as shippingService} from './shipping'
export { default as profitService} from './profits'
export {default as changeService} from './changes'